kulturnat = {};
kulturnat.we = [
  "Vi blev tortureret",
  "Vi holder ikke frem til pensionsalderen",
  "Vi har brug for et nyt stort skibsværft",
  "Vi er nødt til at lyve for at få en ambulance",
  "Vi slap nådigt",
  "Vi skylder mere til det offentlige",
  "Vi vil få mere ebola i Europa",
  "Vi bruger faktisk læseferien",
  "Vi kan blive det nye Novo",
  "Vi arbejder jo allerede med at begrænse flekslån",
  "Vi gør ikke forskel på borgere",
  "Vi har tavshedspligt",
  "Vi må respektere Enhedslisten i PET-udvalg",
  "Vi skal undgå hovsaløsning på dagpengeområdet",
  "Vi vil ikke tvinges til at tage lærlinge",
  "Vi skal lige ned at vende - men så går det fremad",
  "Vi står på en brændende platform",
  "Vi griber ind i Kobani, hvis koalitionen går efter Assad",
  "Vi har fokus på dårlige antenner",
  "Vi laver altså noget",
  "Vi kender ikke grøntsagerne",
  "Vi giver ikke inklusionsbørn det de har krav på",
  "Vi klapper hash-prisen af på Christiania",
  "Vi skal investere i børn",
  "Vi skal bygge OPP-skoler",
  "Vi har forbud mod at sælge hash på Christiania",
  "Vi er klar til ebola",
  "Vi kan ikke reducere smitterisikoen til nul",
  "Vi løb for livet",
  "Vi finder en fælles løsning",
  "Vi er et kropsforskrækket og pædofiliangst samfund",
  "Vi løser ikke MRSA-problemet ved at teste svinekødet",
  "Vi holder på Eurovision-dokumenter af konkurrencehensyn",
  "Vi spiller nøgen-Twister",
  "Vi trænger til et nyt syn på muskelskader",
  "Vi elsker stadig svinekød",
  "Vi kan få meget mere for idrætspengene",
  "Vi har en pligt",
  "Vi har brug for på ny at tænke det umulige",
  "Vi blev lokket i politisk baghold",
  "Vi vil beholde Helle Thorning",
  "Vi skal være mere åbne",
  "Vi skal ikke detailstyre",
  "Vi tager alle anmeldelser alvorligt",
  "Vi ved ikke hvornår vi kan køre igen",
  "Vi tager sagen seriøst",
  "Vi skal samarbejde om vejarbejde - ikke slås",
  "Vi holder, hvad vi lover",
  "Vi sætter ikke et mål for derefter at gå i en anden retning",
  "Vi bliver angrebet af mafiamedlemmer",
  "Vi kan ikke tage flere lærling",
  "Vi er kun interesseret i, hvad du kan",
  "Vi kan ikke fjerne svine-MRSA",
  "Vi er klar til angreb i Syrien",
  "Vi tager alle de forholdsregler, vi kan",
  "Vi har nøje vurderet risiko for ebola-smitte",
  "Vi kører escort",
  "Vi er klar til at forhandle om atomprogram",
  "Vi sender soldater på en farefuld mission",
  "Vi kan ikke vente til børnene flytter",
  "Vi skal have svesken på disken",
  "Vi laver ukvalificerede afgørelser",
  "Vi skal seriøst have set på de krav",
  "Vi skjuler intet i Eurovision-sag",
  "Vi er i krig med Islamisk Stat",
  "Vi risikerer at danske jihadister går fri",
  "Vi gør hvad som helst for gratis wifi",
  "Vi skal nok stemme for udsendelse af F-16-flyene",
  "Vi kan allerede straffe terrorister hårdt",
  "Vi følger demonstrationer i Hongkong tæt",
  "Vi stemmer om F16-udsendelse torsdag morgen",
  "Vi tror på lige muligheder",
  "Vi er nødt til at spare mere end krav",
  "Vi obducerer for få",
  "Vi tvinges til at lukke 20 uddannelser",
  "Vi har aldrig dækket noget som ebola",
  "Vi er blevet skåret i løn",
  "Vi skal gøre alt for at få Sarah og Yasmin hjem",
  "Vi vil ikke betale for børnenes skole-computere",
  "Vi byggede jo nærmest hele Dybbøl",
  "Vi er hårde nok over for IS-krigere",
  "Vi passede bare vores job",
  "Vi prøver det nye sociale megahit",
  "Vi vil give vores børn væk for gratis wifi",
  "Vi har et politisk ansvar",
  "Vi har afføring i hele området",
  "Vi mangler hjælp",
  "Vi kommer aldrig til at udrydde sygdommen",
  "Vi er glade hver dag",
  "Vi har allerede smartwatches",
  "Vi vil være endnu mere gæstfri",
  "Vi er dygtige og meget respekterede",
  "Vi prøver det nye sociale megahit",
  "Vi vil helst have piger",
  "Vi vil nå de samme mål som Pape",
  "Vi kan ikke vente et år på ny bro",
  "Vi har styr på produktionen",
  "Vi blev ikke advaret om salmonella",
  "Vi er ligeglade med hvor folk er født",
  "Vi er sammen - men bor hver for sig",
  "Vi undervurderede truslen fra IS",
  "Vi tror stadig på IC4",
  "Vi skal lytte mere til patienterne",
  "Vi tør ikke fortælle om SKAT's rocker-metoder",
  "Vi gider ikke høre mere om jeres bro",
  "Vi triller en tur til fortiden og tester Renaults nyeste",
  "Vi går i utakt",
  "Vi bliver sparet væk",
  "Vi kom så hurtigt, vi kunne",
  "Vi når ikke at blive færdige til mandag morgen",
  "Vi har selv sat systemet før mennesket",
  "Vi forsøgte at hjælpe flaskesamleren",
  "Vi har haft blikket stift rettet mod motion og sund kost",
  "Vi græder når vi ser hende",
  "Vi skal være mere gæstfrie over for udlændinge",
  "Vi tjener ikke på dansk film",
  "Vi kan ikke bekæmpe IS udelukkende fra luften",
  "Vi skal over 10 procent",
  "Vi var fælles om det",
  "Vi har selv sat systemet før mennesket",
  "Vi venter stadig på den store konservative sag",
  "Vi farer vild i udlandstakster",
  "Vi føler os meget privilegerede",
  "Vi har kun danset",
  "Vi er stoppet med at putte kødboller i suppen",
  "Vi føler os meget privilegeret",
  "Vi er truet af ny aktienedtur",
  "Vi har ingen oplysninger om terror-angreb på metro",
  "Vi vil have en kattelov",
  "Vi beklager uheldigt ordvalg",
  "Vi drikker mest på motionsdage",
  "Vi er 15-20 år foran rivalerne",
  "Vi er oppe imod meget avancerede hackere",
  "Vi har nået smertegrænsen for flygtninge",
  "Vi sparer mere op til pension - når vi har råd til det",
  "Vi kan måske redde titusindvis af liv",
  "Vi har allerede været fængslet i 40 år",
  "Vi må alle handle hurtigt",
  "Vi har dræbt fransk turist",
  "Vi er nødt til at lave ansigtstatoveringer for at overleve",
  "Vi er fremmede i vores egen by. Den er som et sort hul.",
  "Vi har gode forbindelser til Danmark",
  "Vi er for dårlige til at sælge Esbjerg",
  "Vi finder aldrig en ny trafik-Jette",
  "Vi har strammet op",
  "Vi dør ikke, hvor vi ønsker",
  "Vi er forkælede",
  "Vi ved godt hvad de ledige laver",
  "Vi må »konfrontere, nedbryde og besejre« IS' ideologi",
  "Vi har alle til rådighed værende værktøjer til exit'en",
  "Vi elsker store byer - bare ikke Esbjerg",
  "Vi kan godt forhandle uden IC4-svar",
  "Vi har ikke flyttet os mod venstre",
  "Vi møder ondskab",
  "Vi vurderer ikke lovligheden af USAs angreb",
  "Vi vil komme til at mangle 150.000 udlændinge",
  "Vi er ikke inhabile - vi har jo undersøgt os selv",
  "Vi har dræbt fransk turist",
  "Vi køber stadig dvd'er",
  "Vi vil knuse dødens netværk",
  "Vi er stadig i chok",
  "Vi har ubrugte værdibeviser for 168 millioner kroner",
  "Vi har uddannet os i blinde",
  "Vi vil have Dong-pengene to gange igen",
  "Vi kan ikke tillade os at uddanne til arbejdsløshed",
  "Vi vil åbne 1.500 butikker med Britney",
  "Vi mangler viden om svine-MRSA",
  "Vi kan ikke være bekendt at uddanne til arbejdsløshed",
  "Vi skal stramme skruen overfor boligejerne",
  "Vi støtter op om angrebet mod IS i Syrien",
  "Vi kan stadig afværge katastrofen",
  "Vi ændrer ikke politik",
  "Vi vil hellere se Beatles-musical end Hamlet",
  "Vi var tilfredse",
  "Vi skal tage IS-video meget alvorligt",
  "Vi bager for at opnå prestige",
  "Vi accepterer ikke at blive anklaget for cyberspionage",
  "Vi forsøgte at hjælpe flaskesamler",
  "Vi har standset IS' fremrykning",
  "Vi kæmper mod cyber-spioner 24 timer i døgnet",
  "Vi har også lånt ord fra dem",
  "Vi havde ikke styr på telefonudgifterne",
  "Vi har strammet op på mobil-regninger",
  "Vi får typisk dansk efterårsvejr",
  "Vi skal sende et klart signal til Kina",
  "Vi skal forebygge ekstremismen",
  "Vi har forsømt integrationsområdet",
  "Vi sælger normalt under shitstorm",
  "Vi bliver langt flere på Jorden",
  "Vi må bare fyre den af",
  "Vi klager over politiet",
  "Vi må holde fødderne på jorden",
  "Vi kan godt tale arbejdsmarkedsydelse i finanslov",
  "Vi har ikke følt os truet af dem",
  "Vi har fået en ny forfader",
  "Vi skal være bedre til at sige tingene lige ud",
  "Vi kæmper stadig samme kamp som fagbevægelsen",
  "Vi har forsømt integrationsområdet",
  "Vi påtager os det fulde ansvar",
  "Vi sidder bare her",
  "Vi skal tage større del i den tid, der kommer efter efterskolen",
  "Vi skal nok blive enige med DF",
  "Vi vil give EM-fans en oplevelse",
  "Vi ser spøgelser",
  "Vi står i en ekstraordinær situation",
];

kulturnat.i = [
  "Jeg vil aldrig bringe mig i en situation som Thorning",
  "Jeg er taknemmelig for min behandling",
  "Jeg føler mig bedre tilpas efter at have taget på",
  "Jeg kæmpede med bulimi i 17 år",
  "Jeg ville have gjort det igen",
  "Jeg er ikke modstander af utroskab",
  "Jeg har sklerose",
  "Jeg har aldrig oplevet noget lignende",
  "Jeg gør det, fordi jeg selv har en datter",
  "Jeg har kræft",
  "Jeg vil afsted",
  "Jeg ringede efter hjælp allerede 15.02",
  "Jeg har rockerne bag mig",
  "Jeg forsøgte at lokke Per i slips"
];