kulturnat = {};
kulturnat.we = [
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi har ikke hørt fra USA endnu"
];

kulturnat.i = [
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi taler stadig ikke sammen",
  "Vi får for lidt i løn",
  "Vi ville bare snakke",
  "Vi kan ikke isolere os fra problemerne",
  "Vi bør overveje at sende våben til Syrien",
  "Vi har ikke hørt fra USA endnu"
];